sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t dirklangner/docker-react -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dirklangner/docker-react npm test-- --coverage

after_success:
  - docker build -t dirklangner/multi-client-10-14 ./client
  - docker build -t dirklangner/multi-nginx-10-14 ./nginx
  - docker build -t dirklangner/multi-server-10-14 ./server
  - docker build -t dirklangner/multi-worker-10-14 ./worker
  # Log in to the docker CLI
  - echo "dirklangner" | docker login -u "luzifer&73" --password-stdin
  # Take those images and push them to docker hub
  - docker push dirklangner/multi-client-10-14
  - docker push dirklangner/multi-nginx-10-14
  - docker push dirklangner/multi-server-10-14
  - docker push dirklangner/multi-worker-10-14
